version: "{build}"
build: off
skip_tags: true

environment:
  global:
    KERBEROS_USERNAME: administrator
    KERBEROS_PASSWORD: Password01
    KERBEROS_REALM: example.com
    KERBEROS_PORT: 80

  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - set PATH=%APPDATA%\npm;%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%PATH%
  - npm i

test_script:
  - npm test
